In [4]:
# import dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import hvplot.pandas
from pathlib import Path
import plotly.express as px
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import datetime as dt
from config import db_password

In [5]:
# Load the crypto_data.csv modified dataset includng current 2021 data

file_path = "./resources/listings_cleaned2.csv"
df = pd.read_csv(file_path,index_col=0)
df.head()

,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,zipcode,latitude,...,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_days_active,time_since_first_review,time_since_last_review
id,,,,,,,,,,,,,,,,,,,,,
958,7/31/2008,within a few hours,100%,1,1,1,1,Western Addition,94115,37.76931,...,9.0,1,1,1,0,0,1.60,3958,4+ years,17
7918,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,94117,37.76669,...,8.0,0,9,0,9,0,0.14,3637,4+ years,923
8142,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,94117,37.76487,...,9.0,0,9,0,9,0,0.14,3637,4+ years,263
8339,7/2/2009,within an hour,100%,0,2,2,1,Western Addition,94115,37.77525,...,9.0,0,2,2,0,0,0.23,3622,4+ years,295
8739,1/27/2009,within an hour,100%,1,2,2,0,Mission,94110,37.75919,...,10.0,1,2,0,2,0,5.61,3778,4+ years,12

In [11]:
# create a local server, the connection string

db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/sf_abnb"

In [12]:
engine = create_engine(db_string)

In [16]:
df.to_sql(name='sflistings', con=engine)