In [39]:
%matplotlib inline

# import dependencies
import pandas as pd
import numpy as np
import json
import geopandas as gpd

In [40]:
df = gpd.read_file('./resources/san-francisco.geojson')

df.head(10)

,OBJECTID,DISTRICT,COMPANY,geometry
0,1,CENTRAL,A,"POLYGON ((-122.40532 37.80687, -122.40440 37.8..."
1,2,SOUTHERN,B,"MULTIPOLYGON (((-122.38822 37.79000, -122.3880..."
2,3,BAYVIEW,C,"POLYGON ((-122.39342 37.70841, -122.39349 37.7..."
3,4,MISSION,D,"POLYGON ((-122.40802 37.76940, -122.40767 37.7..."
4,5,PARK,F,"POLYGON ((-122.44665 37.77588, -122.44683 37.7..."
5,6,RICHMOND,G,"POLYGON ((-122.44805 37.78237, -122.44804 37.7..."
6,7,INGLESIDE,H,"POLYGON ((-122.40830 37.70833, -122.41009 37.7..."
7,8,TARAVAL,I,"POLYGON ((-122.45552 37.71099, -122.45560 37.7..."
8,9,NORTHERN,E,"POLYGON ((-122.44565 37.80537, -122.44399 37.8..."
9,10,TENDERLOIN,J,"POLYGON ((-122.41795 37.78602, -122.41654 37.7..."

In [41]:
df = df.drop(['OBJECTID', 'COMPANY'], axis=1)
df.head()

   DISTRICT                                           geometry
0   CENTRAL  POLYGON ((-122.40532 37.80687, -122.40440 37.8...
1  SOUTHERN  MULTIPOLYGON (((-122.38822 37.79000, -122.3880...
2   BAYVIEW  POLYGON ((-122.39342 37.70841, -122.39349 37.7...
3   MISSION  POLYGON ((-122.40802 37.76940, -122.40767 37.7...
4      PARK  POLYGON ((-122.44665 37.77588, -122.44683 37.7...

In [42]:
df.to_csv('./resources/sanfranciscogeo.csv')