In [25]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func
import datetime as dt
from config import db_password

In [26]:
#df = pd.read_csv("Resources//sf_airbnb_listings_modified.csv")
# Change the path to use a different one
file_path = Path("./resources/listings_cleaned2.csv")
df = pd.read_csv(file_path,low_memory=False)
df.head()

,id,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,property_type,...,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_days_active,time_since_first_review,time_since_last_review
0,958,7/31/2008,within a few hours,100%,1,1,1,1,Western Addition,Apartment,...,9.0,1,1,1,0,0,1.60,3958,4+ years,17
1,7918,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,Apartment,...,8.0,0,9,0,9,0,0.14,3637,4+ years,923
2,8142,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,Apartment,...,9.0,0,9,0,9,0,0.14,3637,4+ years,263
3,8339,7/2/2009,within an hour,100%,0,2,2,1,Western Addition,House,...,9.0,0,2,2,0,0,0.23,3622,4+ years,295
4,8739,1/27/2009,within an hour,100%,1,2,2,0,Mission,Other,...,10.0,1,2,0,2,0,5.61,3778,4+ years,12

In [27]:
db_string = f"postgresql://postgres:{db_password}@127.0.0.1:5432/sf_abnb"

In [28]:
engine = create_engine(db_string)

In [29]:
df.to_sql(name='listings', con=engine)

In [50]:
import sqlite3
conn=sqlite3.connect('sf_abnb')
df1= pd.read_sql_query("SELECT * FROM listings", con=engine)
df1.head()

,index,id,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,...,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_days_active,time_since_first_review,time_since_last_review
0,0,958,7/31/2008,within a few hours,100%,1,1,1,1,Western Addition,...,9.0,1,1,1,0,0,1.60,3958,4+ years,17
1,1,7918,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,...,8.0,0,9,0,9,0,0.14,3637,4+ years,923
2,2,8142,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,...,9.0,0,9,0,9,0,0.14,3637,4+ years,263
3,3,8339,7/2/2009,within an hour,100%,0,2,2,1,Western Addition,...,9.0,0,2,2,0,0,0.23,3622,4+ years,295
4,4,8739,1/27/2009,within an hour,100%,1,2,2,0,Mission,...,10.0,1,2,0,2,0,5.61,3778,4+ years,12

In [51]:
df1.drop(columns='index',inplace=True)
df1.head()

,id,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,property_type,...,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_days_active,time_since_first_review,time_since_last_review
0,958,7/31/2008,within a few hours,100%,1,1,1,1,Western Addition,Apartment,...,9.0,1,1,1,0,0,1.60,3958,4+ years,17
1,7918,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,Apartment,...,8.0,0,9,0,9,0,0.14,3637,4+ years,923
2,8142,6/17/2009,within a few hours,100%,0,10,10,1,Haight Ashbury,Apartment,...,9.0,0,9,0,9,0,0.14,3637,4+ years,263
3,8339,7/2/2009,within an hour,100%,0,2,2,1,Western Addition,House,...,9.0,0,2,2,0,0,0.23,3622,4+ years,295
4,8739,1/27/2009,within an hour,100%,1,2,2,0,Mission,Other,...,10.0,1,2,0,2,0,5.61,3778,4+ years,12

In [31]:
df1.columns.tolist()

['index',
 'id',
 'host_since',
 'host_response_time',
 'host_response_rate',
 'host_is_superhost',
 'host_listings_count',
 'host_total_listings_count',
 'host_identity_verified',
 'neighbourhood_cleansed',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bedrooms',
 'beds',
 'price',
 'minimum_nights',
 'maximum_nights',
 'calendar_updated',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'first_review',
 'review_scores_rating',
 'review_scores_accuracy',
 'review_scores_cleanliness',
 'review_scores_checkin',
 'review_scores_communication',
 'review_scores_location',
 'review_scores_value',
 'instant_bookable',
 'calculated_host_listings_count',
 'calculated_host_listings_count_entire_homes',
 'calculated_host_listings_count_private_rooms',
 'calculated_host_listings_count_shared_rooms',
 'reviews_per_month',
 'host_days_active',
 'time_since_first_review',
 'time_since_last_review']

In [53]:
df1= pd.read_sql_query("SELECT host_response_rate FROM listings", con=engine)
df1.head()

  host_response_rate
0               100%
1               100%
2               100%
3               100%
4               100%

In [32]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df2 = df.copy()
cols = ['host_since']
df2[cols] = df2[cols].apply(LabelEncoder().fit_transform)
df2.head()

,id,host_since,host_response_time,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,neighbourhood_cleansed,property_type,...,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,host_days_active,time_since_first_review,time_since_last_review
0,958,1993,within a few hours,100%,1,1,1,1,Western Addition,Apartment,...,9.0,1,1,1,0,0,1.60,3958,4+ years,17
1,7918,1645,within a few hours,100%,0,10,10,1,Haight Ashbury,Apartment,...,8.0,0,9,0,9,0,0.14,3637,4+ years,923
2,8142,1645,within a few hours,100%,0,10,10,1,Haight Ashbury,Apartment,...,9.0,0,9,0,9,0,0.14,3637,4+ years,263
3,8339,1899,within an hour,100%,0,2,2,1,Western Addition,House,...,9.0,0,2,2,0,0,0.23,3622,4+ years,295
4,8739,118,within an hour,100%,1,2,2,0,Mission,Other,...,10.0,1,2,0,2,0,5.61,3778,4+ years,12

In [20]:
df_encoded = pd.get_dummies(df, columns=["host_response_time", "neighbourhood_cleansed"])
df_encoded.head()

,id,host_since,host_response_rate,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,property_type,room_type,accommodates,...,neighbourhood_cleansed_Potrero Hill,neighbourhood_cleansed_Presidio,neighbourhood_cleansed_Presidio Heights,neighbourhood_cleansed_Russian Hill,neighbourhood_cleansed_Seacliff,neighbourhood_cleansed_South of Market,neighbourhood_cleansed_Twin Peaks,neighbourhood_cleansed_Visitacion Valley,neighbourhood_cleansed_West of Twin Peaks,neighbourhood_cleansed_Western Addition
0,958,7/31/2008,100%,1,1,1,1,Apartment,Entire home/apt,3,...,0,0,0,0,0,0,0,0,0,1
1,7918,6/17/2009,100%,0,10,10,1,Apartment,Private room,2,...,0,0,0,0,0,0,0,0,0,0
2,8142,6/17/2009,100%,0,10,10,1,Apartment,Private room,2,...,0,0,0,0,0,0,0,0,0,0
3,8339,7/2/2009,100%,0,2,2,1,House,Entire home/apt,5,...,0,0,0,0,0,0,0,0,0,1
4,8739,1/27/2009,100%,1,2,2,0,Other,Private room,3,...,0,0,0,0,0,0,0,0,0,0

In [12]:
df_encoded.describe()

,id,host_is_superhost,host_listings_count,host_total_listings_count,host_identity_verified,accommodates,bedrooms,beds,price,minimum_nights,...,neighbourhood_cleansed_Potrero Hill,neighbourhood_cleansed_Presidio,neighbourhood_cleansed_Presidio Heights,neighbourhood_cleansed_Russian Hill,neighbourhood_cleansed_Seacliff,neighbourhood_cleansed_South of Market,neighbourhood_cleansed_Twin Peaks,neighbourhood_cleansed_Visitacion Valley,neighbourhood_cleansed_West of Twin Peaks,neighbourhood_cleansed_Western Addition
count,1.015300e+04,10153.000000,10153.000000,10153.000000,10153.000000,10153.000000,9425.000000,9972.000000,10153.000000,1.015300e+04,...,10153.000000,10153.000000,10153.000000,10153.000000,10153.000000,10153.000000,10153.000000,10153.000000,10153.000000,10153.000000
mean,1.955918e+07,0.508618,35.736827,35.736827,0.746085,3.222299,1.449655,1.821400,214.417512,9.864565e+03,...,0.030139,0.000985,0.003349,0.021865,0.002659,0.058308,0.009061,0.009751,0.017729,0.071210
std,1.440093e+07,0.499950,185.959874,185.959874,0.435271,1.916841,0.903819,1.214483,363.594047,9.924365e+05,...,0.170978,0.031370,0.057774,0.146251,0.051502,0.234336,0.094764,0.098268,0.131970,0.257189
min,9.580000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.764924e+06,0.000000,1.000000,1.000000,0.000000,2.000000,1.000000,1.000000,99.000000,2.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.849272e+07,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,1.000000,150.000000,3.000000e+00,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2.963710e+07,1.000000,5.000000,5.000000,1.000000,4.000000,2.000000,2.000000,240.000000,3.000000e+01,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,5.298956e+07,1.000000,1987.000000,1987.000000,1.000000,16.000000,14.000000,14.000000,25000.000000,1.000000e+08,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
y = df["price"]
X = df.drop(columns="price")

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [14]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(solver='lbfgs', random_state=1)
classifier

LogisticRegression(random_state=1)

In [16]:
LogisticRegression(random_state=1, solver='lbfgs')

LogisticRegression(random_state=1)

In [33]:
classifier.fit(X_train, y_train)

ValueError: could not convert string to float: 'https://www.airbnb.com/rooms/35836829'